server:
  port: 8082

spring:
  datasource:
   url: jdbc:postgresql://localhost:5433/microservices
   username: postgres
   password: Punit@92655
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: hotel-service
  config:
    import: configserver:http://localhost:8085
okta:
  oauth2:
    issuer: https://dev-52635044.okta.com/oauth2/default
    audience: api://default