server:
  port: 8081

spring:
  datasource:
   url: jdbc:mysql://localhost:3306/microservices
   username: punitt
   password: Punit@92655
   driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52635044.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaej6rdzvLDNdUhc5d7
            client-secret: Xk2Sv0U0cC_sjqBbKCAu0LhUI7YPsGbMSy7bIFyq3ZSq9chTJNlTTNcWBkoGwNi0
        provider:
          okta:
            issuer-uri: https://dev-52635044.okta.com/oauth2/default
  

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  # retry:
  #   instances:
  #     ratingHotelBreaker:
  #       max-attempts: 3
  #       wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
okta:
  oauth2:
    issuer: https://dev-52635044.okta.com/oauth2/default
    audience: api://default
      
