server:
  port: 8083

spring:
  data:
    mongodb:    
        uri: "mongodb+srv://punittewaniext:ZSL2Gt7EiXceI0ic@cluster0.gjrnoqd.mongodb.net/?retryWrites=true&w=majority"
        database: "ratingservice"
  application:
    name: rating-service
  config:
    import: configserver:http://localhost:8085
okta:
  oauth2:
    issuer: https://dev-52635044.okta.com/oauth2/default
    audience: api://default 

